name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json') }}
        restore-keys: node-${{ hashFiles('package-lock.json') }}

    - name: Cache Pods
      uses: actions/cache@v1
      with:
        path: Pods
        key: pods-${{ hashFiles('Podfile.lock') }}
        restore-keys: pods-${{ hashFiles('Podfile.lock') }}

    - name: Install Firebase Tools
      run: make setup

    - name: Bundle install
      run: bundle

    - name: Pod install
      run: bundle exec pod install

    - name: Build
      run: bundle exec fastlane build

    - name: Run Unit Test
      run: make test
